Barks for NPCs during Missions
FinnbarrOC/EspionAge pull request #313
Opened 2020-03-28 20:13 UTC by chadleytan

Implemented the basis for NPC barks during missions. Would love if any of you can try it and give feedback for ways to improve. Still a work in progress to make it better but it is functioning properly. Also please give advice on how to improve coding wise cause its super janky and wanky. Definitely needs tons of improvement :)

<img width="649" alt="Screen Shot 2020-03-28 at 4 12 33 PM" src="https://user-images.githubusercontent.com/28247345/77832805-06c14900-710f-11ea-8d55-40a08d44514e.png">

Main changes:
* Added a bark manager `BarkManager.cs` which is responsible for holding all barks
   * Drag and drop bark to corresponding event which are enums
<img width="344" alt="Screen Shot 2020-03-28 at 3 54 48 PM" src="https://user-images.githubusercontent.com/28247345/77832492-f60fd380-710c-11ea-988a-2d432562632a.png">

* Created a script called `NPCReactiveBark.cs` which handles which bark is called by the NPC
   * Must set which mission this NPC will be a part of as it will load the appropriate barks for that mission on start (Idle, Spotted, Lost & Noise)
   * Added this script to the Nurse_Steve_Patroller prefab but I think we would have to make another prefab for any other NPCs in other missions if we instantiate because we would have to set the MissionsEnum property to the appropriate misssion to load the correct barks for the patrolling NPCs

--
Some other changes:
* Small changes to animation of (A) button
* Hiding of (A) button on interaction
* Rescaling of speech bubble based NPC distance away from Birdie
* Bug Fixes
Completes #297 
Fixes #277

2020-03-28 23:17 UTC, jurcaua requested changes
oooooof rdy for this baby! and happy to see it wasnt too hard to implement with our current systems!!

some comments for cleaning it up but otherwise looks good!

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +        currentTime += Time.deltaTime;
Instead of using a variable for currentTime, can we use use `Time.time`?

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +    public float randomNum; // Used to have randomized time for next idle bark
Does this need to be public?

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +            if (currentTime - timeLastHiddenBark >= (15f + randomNum))
Instead of this logic with the hardcoded 15f and values for the randomNum, can we do something like
have a public range (using NaughtyAttributes, they have a range thing u can use: https://dbrizov.github.io/na-docs/attributes/drawer_attributes/min_max_slider.html)
where we just straight up only need to get a random number between this range

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +        if (playerStatus != PlayerDetectionStatus.Visible)
Logic here i think can be simplified to 

```
 if (playerStatus == PlayerDetectionStatus.Hidden)
{
...
}
else  if (playerStatus == PlayerDetectionStatus.ChasedNotVisible)
{
...

}
```

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +        }
Since this is the only coroutine you're dealing with, we can remove this and the coroutine ref and just call `StopAllCoroutines()`

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +    private void ReactievBark()
type in function name!

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +        if (currentTime - timeLostVision >= 3.0f && playerStatus != PlayerDetectionStatus.Visible)
Having this 3f be a public variable would be useful!

2020-03-28 23:17 UTC, jurcaua commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +        timeLastHiddenBark = currentTime;
```suggestion
        timeLastHiddenBark = Time.time;
```

2020-03-28 23:53 UTC, chadleytan commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +    public float randomNum; // Used to have randomized time for next idle bark
naw was using it to debug haha

2020-03-28 23:54 UTC, chadleytan commented on Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs
> +            if (currentTime - timeLastHiddenBark >= (15f + randomNum))
kk I'll change it!

2020-03-29 03:19 UTC, jurcaua approved these changes
beautiful work sir!!!!! gonna add so much life to the game :)

2020-03-29 19:46 UTC, merged